"use client";
import Header from "./components/Header";
import { AuthProvider } from "./context/AuthContext";
import { AppProvider } from "./context/Context";
import { FilterContextProvider } from "./context/FilterContext";
import Providers from "./context/Provider";
import "./globals.css";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-gray-100 dark:bg-zinc-900 transition-all duration-700 overflow-x-hidden w-full"
        suppressHydrationWarning={true}
      >
        <AppProvider>
          <FilterContextProvider>
            <AuthProvider>
              <Providers>
              <ToastContainer
                  position="top-right"
                  autoClose={2000}
                  hideProgressBar={false}
                  newestOnTop={false}
                  closeOnClick
                  rtl={false}
                  pauseOnFocusLoss
                  draggable
                  pauseOnHover
                  theme="light"
                />
                <Header />
                <div className="w-screen flex justify-center items-center dark:bg-zinc-900">
                  <div className="w-full custom-container flex justify-center items-center px-5">
                 
                    {children}
                  </div>
                </div>
              </Providers>
            </AuthProvider>
          </FilterContextProvider>
        </AppProvider>
      </body>
    </html>
  );
}
