import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import GlobalWrapper from "./lib/GlobalWrapper";

export const metadata = {
  title: "Newstimes",
  description: "Generated by create next app",
  icon: "https://i.ytimg.com/vi/GHAXJA1-kw0/maxresdefault.jpg"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className="bg-gray-100 dark:bg-zinc-900 transition-all duration-700 overflow-x-hidden  w-screen min-h-screen"
        suppressHydrationWarning={true}
      >
        <GlobalWrapper>{children}</GlobalWrapper>
      </body>
    </html>
  );
}
