import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import GlobalWrapper from "./lib/GlobalWrapper";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className={`${inter.className}  bg-gray-100 dark:bg-zinc-900 transition-all duration-700 overflow-x-hidden w-full`}
        suppressHydrationWarning={true}
      >
        <GlobalWrapper>{children}</GlobalWrapper>
      </body>
    </html>
  );
}
