
export const newsdata = [
  {
    "author": null,
    "title": "Fed officials divided in July over need for more rate hikes, minutes show",
    "description": "US Treasury yields hit session highs after the release of the minutes while US stocks extended losses. The dollar was trading higher against a basket of currencies.",
    "url": "https://www.businesstoday.in/latest/world/story/fed-officials-divided-in-july-over-need-for-more-rate-hikes-minutes-show-394399-2023-08-17?utm_source=rssfeed",
    "source": "Business Today | Latest Stock Market And Economy News India",
    "image": null,
    "category": "business",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T01:45:54+00:00"
  },
  {
    "author": null,
    "title": "Gautam Saha appointed interim V-C of BCKV",
    "description": "Gautam Saha appointed interim V-C of BCKV",
    "url": "https://www.thehindu.com/news/national/other-states/gautam-saha-appointed-interim-v-c-of-bckv/article67204281.ece",
    "source": "The Hindu",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T03:21:43+00:00"
  },
  {
    "author": null,
    "title": "IRFC shares plunge 6%, a day after hitting record high. Here's why",
    "description": "IRFC shares fell 5.66 per cent to hit a low of Rs 48.29 on BSE. The stock is up 49 per cent year-to-date and 130 per cent in the last one year.",
    "url": "https://www.businesstoday.in/markets/company-stock/story/irfc-shares-plunge-6-a-day-after-hitting-record-high-heres-why-394427-2023-08-17?utm_source=rssfeed",
    "source": "businesstoday",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T04:33:52+00:00"
  },
  {
    "author": null,
    "title": "Landslides block highway in Manipur, at least 500 trucks stranded",
    "description": "At least 500 goods vehicles are stranded in different parts of the Imphal-Silchar highway due to the landslides",
    "url": "https://www.thehindu.com/news/national/other-states/landslides-block-highway-in-manipur-at-least-500-trucks-stranded/article67204363.ece",
    "source": "The Hindu",
    "image": "https://th-i.thgim.com/public/incoming/r9ozt2/article67204380.ece/alternates/LANDSCAPE_1200/PTI08_16_2023_000208B.jpg",
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T04:51:06+00:00"
  },
  {
    "author": null,
    "title": "CBDT notifies new rules to calculate policy maturity proceeds, no exemptions under 10(10D) for high-premium life insurance",
    "description": "In a significant move, the regulatory body has ordained that Section 10 (10) of the Income Tax Act will not apply to policies with a premium above Rs 5 lakh. The clause is effective from April 1, 2023.",
    "url": "https://www.businesstoday.in/personal-finance/tax/story/cbdt-notifies-new-rules-to-calculate-policy-maturity-proceeds-no-exemptions-under-1010d-for-high-premium-life-insurance-394446-2023-08-17?utm_source=rssfeed",
    "source": "businesstoday",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T05:46:12+00:00"
  },
  {
    "author": null,
    "title": "AI vs Journalism: The New York Times considers legal action against OpenAI amid copyright tensions",
    "description": "Recent discussions between The Times and the developers of ChatGPT have been marked by tense negotiations aimed at reaching a licensing agreement",
    "url": "https://www.businesstoday.in/technology/news/story/ai-vs-journalism-the-new-york-times-considers-legal-action-against-openai-amid-copyright-tensions-394423-2023-08-17?utm_source=rssfeed",
    "source": "businesstoday",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T07:16:11+00:00"
  },
  {
    "author": null,
    "title": "Monsoon mayhem: Over 80 killed as heavy rain batters Himachal, Uttarakhand, flash floods in Punjab; top updates",
    "description": "More than 960 people have been rescued while over 10,000 have been shifted to safer places in the regions of Himachal Pradesh, Uttarakhand and Punjab battered by heavy rains and flash floods.",
    "url": "https://www.businesstoday.in/latest/in-focus/story/monsoon-mayhem-over-80-killed-as-heavy-rain-batters-himachal-uttarakhand-flash-floods-in-punjab-top-updates-394475-2023-08-17?utm_source=rssfeed",
    "source": "Business Today | Latest Stock Market And Economy News India",
    "image": null,
    "category": "business",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T07:30:37+00:00"
  },
  {
    "author": null,
    "title": "Bear attack on Dalal Street: Sensex falls about 500 pts, Nifty below 19,350",
    "description": "BSE Sensex dropped about 500 points to trade at 65,046, while NSE's Nifty50 dropped about 130 points to hover around 19,335.50 during the day.",
    "url": "https://www.businesstoday.in/markets/market-commentary/story/bear-attack-on-dalal-street-sensex-falls-about-500-pts-nifty-below-19350-394482-2023-08-17?utm_source=rssfeed",
    "source": "businesstoday",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T07:52:49+00:00"
  },
  {
    "author": null,
    "title": "Stocks to buy: 2 hotel shares that can deliver up to 27% returns",
    "description": "JM Financial said Chalet Hotels is well-placed to benefit from the imminent upcycle due to limited room supply coming in the subject micro-markets.",
    "url": "https://www.businesstoday.in/markets/company-stock/story/stocks-to-buy-2-hotel-shares-that-can-deliver-up-to-27-returns-394445-2023-08-17?utm_source=rssfeed",
    "source": "businesstoday",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T05:43:19+00:00"
  },
  {
    "author": null,
    "title": "‘Huge budget’ for e-courts project will help make lower court tech-friendly, says CJI D.Y. Chandrachud",
    "description": "‘Huge budget’ for e-courts project will help make lower court tech-friendly, says CJI D.Y. Chandrachud",
    "url": "https://www.thehindu.com/news/national/huge-budget-for-e-courts-project-will-help-make-lower-court-tech-friendly-says-cji-dy-chandrachud/article67204687.ece",
    "source": "The Hindu",
    "image": "https://th-i.thgim.com/public/incoming/bypoxe/article67204728.ece/alternates/LANDSCAPE_1200/IMG_DY_Chandrachud_atten_2_1_4KBKEVEP.jpg",
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T07:33:14+00:00"
  },
  {
    "author": null,
    "title": "Air India launches four-day ticket sale for domestic, intl routes: Check dates, prices",
    "description": "Bookings between September 1 and October 31 to be on discounted prices till August 20, says Air India",
    "url": "https://www.businesstoday.in/latest/corporate/story/air-india-launches-four-day-ticket-sale-for-domestic-intl-routes-check-dates-prices-394497-2023-08-17?utm_source=rssfeed",
    "source": "Business Today | Latest Stock Market And Economy News India",
    "image": null,
    "category": "business",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T09:01:11+00:00"
  },
  {
    "author": null,
    "title": "Top Tamil Nadu news developments today",
    "description": "Here is a list of top news developments from Tamil Nadu to look out for on Thursday, August 17, 2023",
    "url": "https://www.thehindu.com/news/national/tamil-nadu/top-tamil-nadu-news-developments-on-august-17-2023/article67204294.ece",
    "source": "The Hindu",
    "image": "https://th-i.thgim.com/public/incoming/vwrpk1/article67196720.ece/alternates/LANDSCAPE_1200/IMG_CM_DMK_MK_STALIN_VAI_2_1_FJBKBD3L.jpg",
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T03:39:40+00:00"
  },
  {
    "author": null,
    "title": "Bata India in talks with Adidas for strategic partnership in Indian market: Report",
    "description": "The report further mentioned that the talks are likely at an advanced stage and the deal contours are in the works",
    "url": "https://www.businesstoday.in/latest/corporate/story/bata-india-in-talks-with-adidas-for-strategic-partnership-in-indian-market-report-394440-2023-08-17?utm_source=rssfeed",
    "source": "Business Today | Latest Stock Market And Economy News India",
    "image": null,
    "category": "business",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T05:31:54+00:00"
  },
  {
    "author": null,
    "title": "Child onboard Delhi-Frankfurt flight sustained injuries due to spillage of hot beverage",
    "description": "Incident unfortunate, all medical expenses will be reimbursed, says Vistara airlines",
    "url": "https://www.thehindu.com/news/national/child-onboard-delhi-frankfurt-flight-sustained-injuries-due-to-spillage-of-hot-beverage/article67204550.ece",
    "source": "The Hindu",
    "image": "https://th-i.thgim.com/public/incoming/qmtni8/article67204572.ece/alternates/LANDSCAPE_1200/6744_18-9-2020_13-50-9_2_08_INDEX_AIRCRAFT_18_09_DEL.JPG",
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T06:21:05+00:00"
  },
  {
    "author": "SportsCafe Desk",
    "title": "FIDE World Cup | R Pragganandhaa still alive, Gukesh and Gujarathi ousted",
    "description": "On Wednesday, Indian Grandmasters D Gukesh and Vidit Gujarathi bowed out of the FIDE World Cup after losing to Norwegian Magnus Carlsen and Azerbaijan's Nijat Abasov, respectively. On the other hand, R Pragganandhaa bounced back after losing the first game, against Arjun Erigaisi to force tie-break.",
    "url": "https://sportscafe.in/chess/articles/2023/aug/17/fide-world-cup-r-pragganandhaa-still-alive-gukesh-and-gujarathi-ousted?utm_medium=rss",
    "source": "Sportscafe",
    "image": "//sportscafe.in/{https}://sportscafe.in/img/es3-cfill-w480-h240/articles/pragg%20chessbase.scorimg.webp",
    "category": "sports",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T07:16:58+00:00"
  },
  {
    "author": null,
    "title": "‘Nehruji known for his work, not just name’: Rahul Gandhi attacks BJP on decision to rename NMML  ",
    "description": "Gandhi’s comments came days after the Modi government decided to rename the Nehru Memorial Museum and Library (NMML) located in New Delhi to the Prime Minister’s Museum and Library Society.",
    "url": "https://www.businesstoday.in/latest/politics/story/nehruji-known-for-his-work-not-just-name-rahul-gandhi-attacks-bjp-on-decision-to-rename-nmml-394502-2023-08-17?utm_source=rssfeed",
    "source": "Business Today | Latest Stock Market And Economy News India",
    "image": null,
    "category": "business",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T09:31:33+00:00"
  },
  {
    "author": null,
    "title": "What happens to your life insurance policy after divorce? Here is what you should do",
    "description": "The most important thing to do is to inform your insurer about the change",
    "url": "https://www.businesstoday.in/personal-finance/insurance/story/what-happens-to-your-life-insurance-policy-after-divorce-here-is-what-you-should-do-394469-2023-08-17?utm_source=rssfeed",
    "source": "businesstoday",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T07:13:39+00:00"
  },
  {
    "author": null,
    "title": "Cipla shares in focus today as FDA licence of Patalganga unit suspended for 10 days",
    "description": "Cipla shares ended flat at Rs 1242, rising 0.56% or Rs 6.95 on BSE against the previous close of Rs 1235.20.",
    "url": "https://www.businesstoday.in/markets/company-stock/story/cipla-shares-in-focus-today-as-fda-licence-of-patalganga-unit-suspended-for-10-days-394416-2023-08-17?utm_source=rssfeed",
    "source": "businesstoday",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T03:27:11+00:00"
  },
  {
    "author": null,
    "title": "Glenmark Pharma shares gain as USFDA gives nod to Tacrolimus ointment",
    "description": "Glenmark Pharma: According to IQVIATM sales data for the 12‐month period ending June 30, the Protopic Ointment, 0.03 per cent achieved annual sales of approximately $15.4 million.",
    "url": "https://www.businesstoday.in/markets/company-stock/story/glenmark-pharma-shares-gain-as-usfda-gives-nod-to-tacrolimus-ointment-394421-2023-08-17?utm_source=rssfeed",
    "source": "businesstoday",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T03:57:25+00:00"
  },
  {
    "author": null,
    "title": "Sangani Hospitals makes a mild debut at D-st; stock lists at 10% premium at Rs 44",
    "description": "The initial public offering of Sangani Hospital was open for subscription between August 4 to August 8 as the company raised Rs 15.17 crore by selling shares in the range of Rs 37-40 apiece.",
    "url": "https://www.businesstoday.in/markets/company-stock/story/sangani-hospitals-makes-a-mild-debut-at-d-st-stock-lists-at-10-premium-at-rs-44-394436-2023-08-17?utm_source=rssfeed",
    "source": "businesstoday",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T05:12:39+00:00"
  },
  {
    "author": null,
    "title": "Another leopard captured on Tirumala foot path",
    "description": "Incidentally it is the exactly the same cage set up in the vicinity of Narasimha swamy temple on the footpath where a leopard was trapped three days back on August 14",
    "url": "https://www.thehindu.com/news/national/andhra-pradesh/another-leopard-captured-on-tirumala-foot-path/article67204225.ece",
    "source": "The Hindu",
    "image": "https://th-i.thgim.com/public/incoming/lwopmh/article67204288.ece/alternates/LANDSCAPE_1200/Leopard.jpeg",
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T03:31:03+00:00"
  },
  {
    "author": null,
    "title": "Congress MLA Birajit Sinha writes to Tripura Assembly Speaker for security, alleging threat to life from mafia",
    "description": "Congress leader Birajit Sinha said, “I hope the competent authority will take proper steps for my safety.”",
    "url": "https://www.thehindu.com/news/national/congress-mla-birajit-sinha-writes-to-tripura-assembly-speaker-for-security-alleging-threat-to-life-from-mafia/article67204479.ece",
    "source": "The Hindu",
    "image": "https://th-i.thgim.com/public/business/Industry/sebi92/article67204509.ece/alternates/LANDSCAPE_1200/vbk-Birajit%20Sinha-x%40BirajitSinhaINC.jpg",
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T05:59:40+00:00"
  },
  {
    "author": null,
    "title": "NCLAT to hear IDBI Bank’s appeal against Zee Entertainment on Aug 31",
    "description": "IDBI Bank had filed the plea in December 2022 before the Mumbai bench seeking insolvency proceedings against Zee Entertainment.",
    "url": "https://www.businesstoday.in/latest/corporate/story/nclat-to-hear-idbi-banks-appeal-against-zee-entertainment-on-aug-31-394492-2023-08-17?utm_source=rssfeed",
    "source": "Business Today | Latest Stock Market And Economy News India",
    "image": null,
    "category": "business",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T08:22:17+00:00"
  },
  {
    "author": null,
    "title": "Uzbekistan says contaminated Indian cough syrup that killed 65 children was on market due to bribery: Report",
    "description": "In Uzbekistan, a total of 21 people have been put on trial, 20 of whom are Uzbeks and one Indian, over the deaths of these children.",
    "url": "https://www.businesstoday.in/industry/pharma/story/uzbekistan-says-contaminated-indian-cough-syrup-that-killed-65-children-was-on-market-due-to-bribery-report-394428-2023-08-17?utm_source=rssfeed",
    "source": "Business Today | Latest Stock Market And Economy News India",
    "image": null,
    "category": "business",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T04:39:46+00:00"
  },
  {
    "author": null,
    "title": "Value Trap or Trapped Value? What should investors do with Bajaj Consumer, Emami and Jyothy Labs?",
    "description": "In this article, let's talk about 3 stocks from the Consumer Staples and Discretionary sector – Bajaj Consumer, Emami and Jyothy Labs.",
    "url": "https://www.businesstoday.in/markets/company-stock/story/value-trap-or-trapped-value-what-should-investors-do-with-bajaj-consumer-emami-and-jyothy-labs-394439-2023-08-17?utm_source=rssfeed",
    "source": "businesstoday",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "in",
    "published_at": "2023-08-17T05:31:42+00:00"
  }
]
  